admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

bravo_shop:
    resource: "@BravoShopBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
